### ISSUE TITLE
Typo detected in the website

### ISSUE THREAD

**Issue by arjunthazhath2001** [KitsuneKode/Crypto-Wallet#2]
Hi, I was checking out "creepy wallet" web app. Simple and elegant UI. Everything looks perfect but found a small typo in the website as well as the popup when the user clicks on "View all Wallet".

1. "Ethereum" being spelled as "Ethireum":
<img width="816" alt="creepywallet issue img1" src="https://github.com/user-attachments/assets/96da4bad-93fa-46a0-b1e0-8fc298421fd3">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/a297f2a5-3644-41e7-9ce3-114c20c3d3ec">

2. The popup reads "All Sol Wallets" but both solana and ethereum wallets are shown below that:
<img width="960" alt="image" src="https://github.com/user-attachments/assets/54902cd8-f6e1-48b0-b736-d362c830310b">
I would suggest to include one more title "All Eth Wallets" just above the ethereum wallets to prevent confusion among users.

Thanking you.
Arjun Thazhath

**Comment by arjunthazhath2001** [comment]
I would be really happy if you could assign me this issue. It will be one of my first real open source contribution. Thanks in advance.

**Comment by KitsuneKode** [comment]
> I would be really happy if you could assign me this issue. It will be one of my first real open source contribution. Thanks in advance.



Thank you for bringing this to my attention! I understand your situation, but I don't think fixing typos would be of no benefit to you. I would gladly assign you some kind of enhancement or issues that affect the UI/UX or any other functionality!

**Comment by KitsuneKode** [comment]
The typos are fixed on the latest commit!

**Comment by arjunthazhath2001** [comment]
> > I would be really happy if you could assign me this issue. It will be one of my first real open source contribution. Thanks in advance.
> 
> Thank you for bringing this to my attention! I understand your situation, but I don't think fixing typos would be of no benefit to you. I would gladly assign you some kind of enhancement or issues that affect the UI/UX or any other functionality!

Sure sir. If you have anyother enhancement or UI/UX issue, please feel free to assign me. Thankyou.
